### ISSUE TITLE
Switch to a unique CryptoNight variant for v9

### ISSUE THREAD

**Issue by wowario** [wownero/wownero#15]
Miners that use rental hash from services like [Nicehash](https://www.nicehash.com/algorithm/cryptonightv7) and [MiningRigRentals](https://www.miningrigrentals.com/rigs/cryptonotev7) dramatically push up the difficulty rate, hop over to other coins with lower difficulty, and then return when difficulty comes back down. This practice is unfair to loyal miners and perpetrates systemic instability for small networks (stuck chains, volatile network hashrates). To combat this issue, we should adopt a custom CryptoNight variant in the next fork. This will not solve the problem, but could provide some security by obscurity.

**Comment by brinstarnetworks** [comment]
The issue is abusive use of Nicehash like @wowario mentions is the problem, not Nicehash in general. There is nothing wrong with a long term job at a reasonable hashrate - it's a sensible option for somebody who wants to mine but doesn't have the physical space or time required for a farm. I can agree this is a fast solution but it's not a permanent solution by any means, nor does it help in any other similar situation not involving Nicehash - we're still vulnerable to any large private farm doing the same type of abusive tactic.

**Comment by Bathmat** [comment]
I vote switch to V7 Heavy! Slow blocks + slow hashrate = stable ;)

**Comment by mattcode55** [comment]
~~we need to switch to CRC32 for maximum wow~~

I think [the Monero Research Lab (or maybe it's just hyc) are developing something fancy and new as a PoW](https://github.com/hyc/randprog), maybe it would be worthwhile waiting for that.

**Comment by jwinterm** [comment]
It's just hyc afaik at this point, and I think it's pretty far off in the
future. Personally I'm more inclined to focus on merge mining with Monero
and tracking their changes, but that's also probably far off in future.

**Comment by wowario** [comment]
Discussion moved to https://github.com/wownero/meta/issues/3
