### ISSUE TITLE
[PROPOSAL] Enable Tor/i2p anonymity networking by default

### ISSUE THREAD

**Issue by wowario** [wownero/wownero#262]
Wownero should have Tor/i2p enabled by default for both broadcasting transactions and p2p syncing. Current available i2p routers include [i2p-zero](https://github.com/i2p-zero/i2p-zero) and [tini2p](https://gitlab.com/tini2p/tini2p). @anonimal Sekreta agnostic approach to mix-networks looks promising.

**Comment by qvqc** [comment]
This would be wow!

When enabled by default, do you mean that it should be proxy aware and it should 'turn on' anonymous transactions if a local router is available?  I think its bad form to include proxyrouting software in the wownerod or wallet-cli.  Instead we should add them as install/build dependencies to the wownero install/build process.    Maybe including a router binary in wowlite wouldn't be that bad, if its possible.

I tried to run wownerod and monerod p2p over tor/i2p only connections today and the code seems to block certain kinds of peers that were not on clear-net.  Weird levin handshake problems that I couldn't find much detail on. Running a pure p2p node over tor/i2p might be really hard unless someone can get their hands dirty on the networking code.

Also do you know [i2pd](https://github.com/PurpleI2P/i2pd) ?  If your looking for a non-java option it seems to have more client functionality that tini2p currently.

It looks like sekreta still has some hurdles to get over before getting included, but looks awesome.

**Comment by wowario** [comment]
By default, I mean the same way Tor is integrated with [Bisq](https://bisq.network). When a user opens Bisq, the application automatically connects to Tor. They do not need to install or configure Tor separately.

Right now, the Mo/Wownero implementation allows for broadcasting transactions over Tor and i2p proxy, but still relies on clearnet for syncing. This is done to minimize the risk of [sybil attacks](https://github.com/wownero/wownero/blob/master/ANONYMITY_NETWORKS.md) and for faster syncing. Yes, we would need the help of someone that is very familiar with the networking code.

I have heard of i2pd and it could be considered. It is my understanding that there was some [bad blood between different dev teams](https://gitlab.com/kovri-project/kovri-docs/-/blob/master/i18n/en/faq.md#what-were-the-turning-points-that-lead-to-forking-from-i2pd-and-why-are-there-two-i2pd-repositories-one-on-bitbucket-and-one-on-github) back in the day. That was the past and we should be open to using whatever works.

**Comment by qvqc** [comment]
Oh, cool.   Here is some [issue that tracks the bisq integration](https://github.com/bisq-network/bisq/issues/483).

If they do ship the end user binary, they do it because they are a big blobby masterpiece.  I don't think wowd needs to follow the blobyness to get the same result.  However shipping binaries with wowlite is way cool, and of course the future.  If we can launch a second binary in electron adding in tor or i2pd  to wowlite should be trivial.

On the other hand. Having the user install tor and/or i2p during install automatically sets and starts the services.  No reason to include blobbed vitally important security software that could cease to function with out an update.  We can set package dependencies when building packages to require either tor or i2p to install, users choice. 

In order to get this in wowd/cli-wallet, I think we should get the wallet to try connections over a socket/port and then failover to clearnet.  Perhaps the priority of connections and blocking particular connections could be configurable.  Even better maybe have a flag that must be set in order to use a clearnet connection.

**Comment by qvqc** [comment]
looks like seeding has some issue with eclipse attack, so bisq style integration might be step backwards long term for wownerod.  we should look closer at sekreta there.  

wowlite with electron however loooks really good for tor/i2pd bisq style integration.  

wow-app might be able to get some defaults changed to use socks proxy or even torsocks.

**Comment by xmrdsc** [comment]
I can recommend [i2p-zero](https://github.com/i2p-zero/i2p-zero) for what it's worth. It is easy to use and @knaccc keeps it properly up to date. Distributing this package with Wownero should be trivial. 

Whatever we pick, wallet cli/gui's will need a fairly large update to interface with such routers.

**Comment by wowario** [comment]
migrated to https://git.wownero.com/wownero/wownero
