### ISSUE TITLE
Wownero v9 Testnet

### ISSUE THREAD

**Issue by wowario** [wownero/wownero#89]
A [testnet pool](https://testnet.wowne.ro) has been set up to check hash performance of [Cryptonight variant 2](https://github.com/monero-project/monero/pull/4218) with [v2.2 tweaks](https://github.com/monero-project/monero/pull/4404) and the reaction time of [LWMA v2](https://github.com/wownero/wownero/commit/95cf3bebbe0167a38a640c42651b5277628f2d35) difficulty algorithm. The server was community funded by the [Wownero Funding System](https://funding.wownero.com/proposal/3). 

**Server**: 

> testnet.wowne.ro:3333

**Testnet Address**:

> 9z3MQQe9ry3GCwcrWXr5VkQBGqsZeSFuSNee4SgR78FALYBYPJPAJQ4ZKKVSFwwuCgd5ZkHoJ84tfMZyVK11xDkDCMNzmup

Miner: https://github.com/xmrig/xmrig (checkout `dev` branch)
Config file: [config.json](https://paste.ubuntu.com/p/7pr6rBTzsm/)

Payouts and banning has been disabled.

Please post your hash performance compared to Cryptonight variant 1 here.

**Comment by wowario** [comment]
Testnet Blockchain Explorer: http://explorer.wowne.ro:8082

**Comment by Bathmat** [comment]
Successfully tested **xmrig-amd-dev**. Still waiting for final tweak to be merged into **xmr-stak** and I will test that.
```
Rig: Win10 1803
GPUs: RX580 8gb, RX480 4gb, RX570, RX470 (4 total)
CNv1: 3530 h/s
CNv2.2: 3350 h/s
```
This shows CNv2.2 getting 95% h/r of CNv1; however, it does come at a cost. Most of the GPUs were using 5-7 Watts more power in HWMonitor. This was making their power consumption similar to Daggerhashimoto power use. I've noted this in all my testing with CNv2 from the start of the algo implementation. I've done tests reducing power as much as could given Windows tools (aka not modifying bios again), and hr for CNv2.2 is around 90% of CNv1.

**GPU Thread Config**
```
        {
            "index": 0,
            "intensity": 896,
            "worksize": 16,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll_factor": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 0,
            "intensity": 896,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll_factor": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 896,
            "worksize": 16,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll_factor": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 1,
            "intensity": 896,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll_factor": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 896,
            "worksize": 16,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll_factor": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 2,
            "intensity": 896,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll_factor": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 896,
            "worksize": 16,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll_factor": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        },
        {
            "index": 3,
            "intensity": 896,
            "worksize": 8,
            "strided_index": 2,
            "mem_chunk": 2,
            "unroll_factor": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        },
```
This was the best config I could find to have the best performance combined with stability (not causing driver resets after the miner was shutdown). The different worksizes in each thread is not a mistake. I found setting one thread to `worksize: 16` and the other to `worksize: 8` helped achieve stable hashrates more quickly.

**Much more testing**
I've been testing this algo since almost it's inception. Here are some of my other results:
[Initial algo testing](https://github.com/SChernykh/xmr-stak-cpu/issues/1#issuecomment-418227462)
[Initial xmrig-amd testing (pre-2.2 tweak)](https://github.com/SChernykh/xmr-stak-cpu/issues/1#issuecomment-421229792)
[Initial xmr-stak testing (AMD only)](https://github.com/fireice-uk/xmr-stak/issues/1832#issuecomment-421667057)

I have many more comments for testing in those threads, including some initial CUDA testing and Intel CPU testing, so feel free to read through those for more info.

**Comment by Bathmat** [comment]
**xmr-stak** showed similar (identical) performance as xmrig-amd: [xmr-stak test](https://github.com/fireice-uk/xmr-stak/issues/1851#issuecomment-424152685)

**Comment by Bathmat** [comment]
OS: Win10
GPU: GTX-1060 6GB (+150 core, +500 mem = 2000 core, 4300 mem)

CNv1 (CUDA): 520 h/s
CNv1 (OpenCL): 497 h/s
CNv2.2 (OpenCL): **444.5 h/s**
```
    "threads": [
        {
            "index": 0,
            "intensity": 640,
            "worksize": 8,
            "strided_index": 0,
            "mem_chunk": 2,
            "unroll": 1,
            "comp_mode": true,
            "affine_to_cpu": false
        }
    ],
```
